# Generated by Django 5.2 on 2025-04-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'Novo'), ('P', 'Processando'), ('S', 'Enviado'), ('D', 'Entregue'), ('C', 'Cancelado')], default='N', max_length=1),
        ),
    ]
