# Generated by Django 5.2 on 2025-04-24 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_observations_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'Novo'), ('P', 'Processando'), ('PA', 'Pago'), ('S', 'Enviado'), ('D', 'Entregue'), ('F', 'Finalizado'), ('R', 'Devolvido'), ('RF', 'Reembolsado'), ('C', 'Cancelado')], default='N', max_length=2),
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'Novo'), ('P', 'Processando'), ('PA', 'Pago'), ('S', 'Enviado'), ('D', 'Entregue'), ('F', 'Finalizado'), ('R', 'Devolvido'), ('RF', 'Reembolsado'), ('C', 'Cancelado')], max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order')),
            ],
        ),
    ]
