# Generated by Django 5.2 on 2025-05-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'Aguardando pagamento'), ('P', 'Processando'), ('PA', 'Pago'), ('S', 'Enviado'), ('D', 'Entregue'), ('F', 'Finalizado'), ('R', 'Devolvido'), ('RF', 'Reembolsado'), ('C', 'Cancelado')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='status',
            field=models.CharField(choices=[('N', 'Aguardando pagamento'), ('P', 'Processando'), ('PA', 'Pago'), ('S', 'Enviado'), ('D', 'Entregue'), ('F', 'Finalizado'), ('R', 'Devolvido'), ('RF', 'Reembolsado'), ('C', 'Cancelado')], max_length=10),
        ),
    ]
