# Generated by Django 5.2 on 2025-05-02 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status_alter_orderstatuslog_status'),
        ('users', '0003_address_created_at_address_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'Pix'), ('boleto', 'Boleto'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito')], default='credito', max_length=20),
        ),
    ]
