# Generated by Django 5.2 on 2025-09-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_created_at_address_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
